#!/bin/bash

if [ -f /etc/redhat-release ] ;
then
    yum -y install mlocate net-tools curl wget nc unzip tcl expect strace shellcheck nmap nano jq ed bc dc
    updatedb
elif [ -f /etc/os-release ] ;
then
    . /etc/os-release
    [[ "${NAME}" == "Ubuntu" ]] && {
        apt-get install -y mlocate net-tools curl wget netcat unzip tcl tcl-expect strace shellcheck nmap nano jq ed bc dc
    }
    updatedb
fi
